### ISSUE TITLE
 no corre docker 

### ISSUE THREAD

**Issue by AndyGT** [ITAM-DS/big-data#1]
cuando trato de jalar el ubuntu:latest  me sale esto 
2015/01/14 10:50:52 Get https://index.docker.io/v1/repositories/library/ubuntu/images: x509: certificate has expired or is not yet valid

 ya borre imagenes y contenedores y sigue sin funcionar

**Comment by nanounanue** [comment]
¿Puedes documentar más intentos? ¿Y explicar qué pasó?

**Comment by AndyGT** [comment]
despúes  me marcaba este error --->
FATA[0000] Error response from daemon: client and server don't have same version (client : 1.16, server: 1.15) 
 actualicé la version de docker con --> boot2docker download
 y luego lo reinicie -----> boot2docker restart 
 y seguí las instrucciones .. ya sirve 
 fin del comunicado :P
