### ISSUE TITLE
Problemas con Parallel

### ISSUE THREAD

**Issue by MarcosOMtz** [ITAM-DS/big-data#51]
Estimado Adolfo, como te comentaba, tengo problemas al momento de instalar GNU Pararllel y te lo explico en los siguientes puntos:

1.- Al momento de querer instalar y siguiendo los pasos que vienen en el documento visto en clase, el archivo "extracción.log" se crea pero queda vacío ya que los archivos que se extraen de la red se guardan en una carpeta llamada "parallel-2015-0122".
2.- Buscando instalar, desde la terminal me posiciono en la carpeta que se generó en el punto 1 y ejecuto el código: ./configure && make && make install
3.- El resultado que me arroja la terminal es el siguiente:

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether ln -s works... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating config.h
config.status: config.h is unchanged
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in src
make[2]: Nothing to be done for `all'.
Making install in src
 .././install-sh -c -d '/usr/local/bin'
 /usr/bin/install -c parallel sql niceload '/usr/local/bin'
install: /usr/local/bin/parallel: Permission denied
make[2]: *** [install-binSCRIPTS] Error 71
make[1]: *** [install-am] Error 2
make: *** [install-recursive] Error 1

Busqué instalar en la terminal del Docker pero obtuve el mismo resultado.

Le he estado moviendo a la configuración de mi máquina pero tengo temor de crear más problemas que solucionar el asunto de la instalación.

Por lo que requiero de tu apoyo para resolver este asunto.

**Comment by alfonsokim** [comment]
Hola.

Correlo en pasos separados:
`./configure`
`make`

Luego la parte que te da problemas `make install` debes correrla con `sudo`:
`sudo make install` 
Siempre y cuando tu usuario sea sudoer. De esta forma se va a instalar para todos los usuarios.
Si no tienes permisos de sudo o por alguna razón lo quieres instalar en otra ruta (tu home, por ejemplo) correlo con:
`make install --prefix=/home/tu_usuario`

Saludos

**Comment by MarcosOMtz** [comment]
Muchas gracias.

**Comment by nanounanue** [comment]
¿Se resolvió?

**Comment by MarcosOMtz** [comment]
Si, muchas gracias, ya pude instalar Parallel. Ahora voy con postgreSQL.

Saludos.
