### ISSUE TITLE
HTTP 400 en http://www.nuforc.org

### ISSUE THREAD

**Issue by alfonsokim** [ITAM-DS/big-data#66]
Hola a todos!

¿alguien está teniendo problemas para bajar los avistamientos? Yo tengo un error HTTP 400 Bad Request: http://www.nuforc.org/webreports/ndxevent.html

Puede ser que la página se haya caído, o lo que es más seguro, ya me banearon de tanto GET que he hecho en las últimas horas.

Buen fin!!

**Comment by FelipeGerard** [comment]
Hola,

No sé si tú problema sea éste: las bases de ufos no vienen en csv ni nada por el estilo. Son htmls y debes escrappear cada una según yo para convertirlas en tablas manejables.

Saludos

**Comment by alfonsokim** [comment]
Mmm mi problema es otro. No veo la página, como si el servidor estuviera abajo.

**Comment by alfonsokim** [comment]
Ya funciona....
