### ISSUE TITLE
Coma de más Lecture3

### ISSUE THREAD

**Issue by jtmancilla** [ITAM-DS/big-data#81]
En la Lectura 3, en la sección postgreSQL > configuracion > configuracion

sobre la coma en reset_val,

debe ser:
```{sql}
select name, context, unit, setting, boot_val, reset_val
from pg_settings
where name in (
'listen_addresses', 'max_connections', 'shared_buffers',
'effective_cache_size', 'work_mem', 'maintenance_work_mem'
)
order by context, name;
```

### otra observacion

La extension `auto_explain`  ya no existe.

**Comment by nanounanue** [comment]
No pongas dos **errores** en el mismo `issue` es confuso
