### ISSUE TITLE
Sobre la clase del 25 de marzo, 2015

### ISSUE THREAD

**Issue by nanounanue** [ITAM-DS/big-data#88]
@ITAM-DS/big-data-2015 

Hola a todos

Me diagnosticaron una infección viral en transición a bacteriana de oidos y garganta con algunos ruidos raros en el pulmón. No podré asistir a la clase de mañana. :-1: 

Por favor, debemos de organizarnos para reponer la clase. Puede ser el próximo miércoles si lo desean.

Por favor confirmen por aquí que recibieron el mensaje.

Saludos

A.

**Comment by lromang** [comment]
Hola profesor,

Recuperate pronto!! mucho animo. En cuanto a la clase, no podré la
siguiente semana ya que salgo del DF.

Saludos,
Luis.

**Comment by jtmancilla** [comment]
Que te re cuperes Adolfo.

De la misma manera saldre del df.

Gracias

Antonio

**Comment by Sophie-Germain** [comment]
Hola Adolfo,

¡Mejórate pronto y cuídate mucho!

Traigo el pendiente de la tesis (sí, aunque no lo creas). Supongo que no
nos podremos ver sino hasta regresando de Semana Santa.

De ser así, ¿podría ser que nos escribamos por mail para que te diga mis
"avances" y me des feedback al respecto?

Mil gracias,



2015-03-24 14:05 GMT-06:00 Adolfo De Unánue <notifications@github.com>:

**Comment by alfonsokim** [comment]
Recibido!




Igual. No puedo el próximo miércoles. Es semana santa.




Que te mejores!!!

**Comment by nanounanue** [comment]
¿No hay clases el siguiente miércoles?

A.

**Comment by Sophie-Germain** [comment]
Noooo, jeje. Es Semana Santa :D

2015-03-24 14:15 GMT-06:00 Adolfo De Unánue <notifications@github.com>:

**Comment by jared275** [comment]
Ok, que te mejores.

**Comment by nanounanue** [comment]
¡Qué mal me siento!

¿Están de acuerdo si preparo el proyecto de una vez y lo mando?

**Comment by sharop** [comment]
Saludos, que te mejores.

**Comment by Sophie-Germain** [comment]
Nooo, queremos irnos felices a Semana Santa :D

**Comment by nanounanue** [comment]
¿No hay clases en toda la semana en el ITAM?

**Comment by Sophie-Germain** [comment]
nel

**Comment by FelipeGerard** [comment]
Recibido! Que te mejores! También voto en contra de contaminar las vacas jeje

**Comment by andreslechuga** [comment]
Que te mejores para que puedas disfrutar las vacaciones!!!

también voto por la no contaminación de las vacaciones.

**Comment by sgongoray** [comment]
Recibido.

**Comment by AndyGT** [comment]
Adolfo, espero te mejores , toma todas tus medicinas y duerme cual oso
No contamines las  vacaciones que ya tenemos un friego de tarea !! no hay clase toda la siguiente semana 

Saludos :)

**Comment by animalito** [comment]
:dancer: libertaaad! ntc! Mejorese! El proximo miercoles esta medio heavy dos clases seguidas no? Porque no mejor un sabado? Pa que no haya broncas con las chambas? Luego hay unos jefes medio histericos!!! jor

**Comment by MarcosOMtz** [comment]
Enterado, que te mejores.

Enviado desde mi iPhone

**Comment by nanounanue** [comment]
@ITAM-DS/big-data-2015 

¡No se les olvide la tarea!

¡¡Es para mañana!!

**Comment by FelipeGerard** [comment]
Con el pull request con el contenido basta ‘edá?

**Comment by LizContreras** [comment]
Yo apoyo que la reposición sea en sábado.

Mejórate pronto

El 24 de marzo de 2015, 15:23, Andrea Fernández Conde <
notifications@github.com> escribió:

> [image: :dancer:] libertaaad! ntc! Mejorese! El proximo miercoles esta
> medio heavy dos clases seguidas no? Porque no mejor un sabado? Pa que no
> haya broncas con las chambas? Luego hay unos jefes medio histericos!!! jor
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ITAM-DS/big-data/issues/88#issuecomment-85697729>.
>



-- 
Saludos,
Lizbeth Contreras

Tel. 044 55 16 86 11 10

**Comment by sharop** [comment]
Apoyo sabatina
