### ISSUE TITLE
Docker de Hadoop

### ISSUE THREAD

**Issue by felipegerard** [ITAM-DS/big-data#98]
La imagen de `docker-hadoop` no tiene los permisos adecuados :(

**Comment by nanounanue** [comment]
@felipegerard 

Acabo de ejecutar desde el `Dockerfile` en mi compu y no hubo problema. Luego ejecuté con `docker pull nanounanue/docker-hadoop` y tampoco hubo problema ¿Si quitaste todos las imágenes anteriores?

**Comment by nanounanue** [comment]
Y me faltó copiarte las imágenes:

```{bash}
ocker-hadoop git:master ❯ docker images
REPOSITORY                           TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
hadoop_pseudo2                       latest              d14d8fcab31a        47 minutes ago      2.217 GB
nanounanue/docker-hadoop             latest              2e7886d2adea        16 hours ago        2.206 GB
hadoop_pseudo                        latest              444ae13b0277        17 hours ago        2.217 GB
```

Con estas tres funcionó. `hadoop_pseudo` es la que viste en la clase. `hadoop-pseudo2` la creé a partir del `Dockerfile` y la otra la bajé del `dockerhub` con `docker pull...` .

Si te fijas esa pesa lo mismo que la tuya.

¿Cuál fué el procedimiento que seguiste?

**Comment by felipegerard** [comment]
En efecto tengo la misma imagen:

REPOSITORY                    TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
nanounanue/docker-hadoop      latest              2e7886d2adea        21 hours ago        2.206 GB
nanounanue/docker-base        latest              ebdeeaa3c64a        28 hours ago        1.167 GB
felipegerard/postgres-image   latest              8322ff6b6a5e        35 hours ago        1.864 GB

Lo que hago exactamente es:

hadoop|master⚡ ⇒ docker run -ti --rm \
  -e "AUTHORIZED_SSH_PUBLIC_KEY=$(cat ~/.ssh/id_rsa.pub)" \
  -v /Users/Felipe/big-data/alumnos/felipegerard/hadoop/tmp/docker-hadoop-data/:/home/hduser/hdfs-data/ \
  -v /Users/Felipe/big-data/alumnos/felipegerard/hadoop/tmp/docker-hadoop-logs/:/srv/hadoop/logs/ \
  -p 2122:2122 -p 2181:2181 -p 39534:39534 -p 9000:9000 \
  -p 50070:50070 -p 50010:50010 -p 50020:50020 -p 50075:50075 \
  -p 50090:50090 -p 8030:8030 -p 8031:8031 -p 8032:8032 \
  -p 8033:8033 -p 8088:8088 -p 8040:8040 -p 8042:8042 \
  -p 13562:13562 -p 47784:47784 -p 10020:10020 -p 19888:19888 \
nanounanue/docker-hadoop /bin/bash
root@093646de732e:/home/itam# su hduser
hduser@093646de732e:/home/itam$ cd
hduser@093646de732e:~$ pwd
/home/hduser
hduser@093646de732e:~$ ls -l .
total 0
drwxr-xr-x 1 itam staff 68 abr 22 15:37 hdfs-data
hduser@093646de732e:~$ # No es mio. A ver si lo puedo cambiar^C
hduser@093646de732e:~$ exit
exit
root@093646de732e:/home/itam# cd /home/hduser/
root@093646de732e:/home/hduser# ls -l
total 0
drwxr-xr-x 1 itam staff 68 Apr 22 15:37 hdfs-data
root@093646de732e:/home/hduser# chown hduser:hadoop hdfs-data
root@093646de732e:/home/hduser# ls -l
total 0
drwxr-xr-x 1 itam staff 68 Apr 22 15:37 hdfs-data
root@093646de732e:/home/hduser# # No se queja, pero no lo hace. Esta carpeta esta directamente linkeada a la carpeta de mi compu.^C
root@093646de732e:/home/hduser# # Que hacer? :(

No sé qué estará pasando, pero creo que tiene que ver con la carpeta compartida. Incluso si empiezo como hduser, y/o en otra carpeta, checa lo que pasa:

proyecto2|master⚡ ⇒ docker run -ti --rm \
>   -e "AUTHORIZED_SSH_PUBLIC_KEY=$(cat ~/.ssh/id_rsa.pub)" \
>   -v /Users/Felipe/big-data/alumnos/felipegerard/hadoop/tmp/docker-hadoop-data/:/home/hduser/cha-hdfs-data/ \
>   -v /Users/Felipe/big-data/alumnos/felipegerard/hadoop/tmp/docker-hadoop-logs/:/srv/hadoop/cha-logs/ \
>   -p 2122:2122 -p 2181:2181 -p 39534:39534 -p 9000:9000 \
>   -p 50070:50070 -p 50010:50010 -p 50020:50020 -p 50075:50075 \
>   -p 50090:50090 -p 8030:8030 -p 8031:8031 -p 8032:8032 \
>   -p 8033:8033 -p 8088:8088 -p 8040:8040 -p 8042:8042 \
>   -p 13562:13562 -p 47784:47784 -p 10020:10020 -p 19888:19888 \
> --user hduser nanounanue/docker-hadoop /bin/bash
hduser@6f81a4a7dc54:/home/itam$ cd
hduser@6f81a4a7dc54:~$ ls
cha-hdfs-data  hdfs-data
hduser@6f81a4a7dc54:~$ ls -l
total 4
drwxr-xr-x 1 itam   staff    68 Apr 22 15:37 cha-hdfs-data
drwxr-xr-x 4 hduser hadoop 4096 Apr 23 04:24 hdfs-data
hduser@6f81a4a7dc54:~$

Ahora la conectada es cha… y ahora ésa es la que es de itam:staff :(

**Comment by nanounanue** [comment]
@felipegerard  edita tus comentarios en el issue para que se distinga el código del texto

**Comment by nanounanue** [comment]
Puedes repetir el proceso y documentarlo, pero crea una carpeta nueva en tu home. Por favor reporta bien, si no, es muy difícil  ayudarte.

**Comment by felipegerard** [comment]
Se volvió loco el markdown... Cuando le pongo preview sale como tu código, pero al ponerle update comment se bate y se ve feo... Qué tiene de malo que sea esa carpeta? Está en mi carpeta de big-data... :(

**Comment by nanounanue** [comment]
No sé si tiene algo de malo, sólo quiero que hagas el proceso desde el principio. Lo más similar al mío para ver si es MacOSX o qué otra cosa. 

Debes de aprender a reportar errores, es una habilidad muy importante.

Y qué chistoso que sólo a tí te pase lo del `markdown` ¿Cómo lo escribes?

**Comment by felipegerard** [comment]
En un rato vuelvo a hacer el proceso, aunque ya fue desde el principio no? Desde que creé la imagen. Escribo el código así:
```
curl google.com
```
Y en el preview sale bien, pero cuando le pongo ya que salga se hace feo.

**Comment by felipegerard** [comment]
Tengo la imagen correcta:
```
$ docker images
REPOSITORY                    TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
nanounanue/docker-hadoop      latest              2e7886d2adea        41 hours ago        2.206 GB
nanounanue/docker-base        latest              ebdeeaa3c64a        2 days ago          1.167 GB
felipegerard/postgres-image   latest              8322ff6b6a5e        2 days ago          1.864 GB
scipy-felipe                  latest              45b1602499bd        2 weeks ago         2.831 GB
ubuntu-felipe                 latest              8b718a079c4b        2 weeks ago         244.8 MB
spark-prueba                  latest              af1e089cb7b9        2 weeks ago         188.6 MB
predictionio                  latest              3a4f005b5158        3 weeks ago         2.381 GB
ubuntu                        14.04               d0955f21bf24        4 weeks ago         188.3 MB
ubuntu                        14.10               78949b1e1cfd        8 weeks ago         194.4 MB
ubuntu                        latest              2d24f826cb16        8 weeks ago         188.3 MB
hello-world                   latest              e45a5af57b00        3 months ago        910 B
```
Corremos el contenedor:
```
$ docker run -ti --rm \
>   -e "AUTHORIZED_SSH_PUBLIC_KEY=$(cat ~/.ssh/id_rsa.pub)" \
>   -v /Users/Felipe/tmp/docker-hadoop-data/:/home/hduser/hdfs-data/ \
>   -v /Users/Felipe/tmp/docker-hadoop-logs/:/srv/hadoop/logs/ \
>   -p 2122:2122 -p 2181:2181 -p 39534:39534 -p 9000:9000 \
>   -p 50070:50070 -p 50010:50010 -p 50020:50020 -p 50075:50075 \
>   -p 50090:50090 -p 8030:8030 -p 8031:8031 -p 8032:8032 \
>   -p 8033:8033 -p 8088:8088 -p 8040:8040 -p 8042:8042 \
>   -p 13562:13562 -p 47784:47784 -p 10020:10020 -p 19888:19888 \
> nanounanue/docker-hadoop /bin/bash
root@d8e39de00234:/home/itam# su hduser
hduser@d8e39de00234:/home/itam$ cd
hduser@d8e39de00234:~$ pwd
/home/hduser
hduser@d8e39de00234:~$ ls -la
total 24
drwxr-xr-x  9 hduser hadoop 4096 abr 22 07:05 .
drwxr-xr-x 15 root   root   4096 abr 22 07:03 ..
-rw-r--r--  1 hduser hadoop  220 abr 22 07:03 .bash_logout
-rw-r--r--  1 hduser hadoop  880 abr 22 06:58 .bashrc
drwxr-xr-x  1 itam   staff    68 abr 24 00:54 hdfs-data
-rw-r--r--  1 hduser hadoop  675 abr 22 07:03 .profile
drwx------  2 hduser hadoop 4096 abr 22 07:03 .ssh
```
Acá tampoco tengo los permisos:
```
hduser@d8e39de00234:~$ cd /srv/hadoop
hduser@d8e39de00234:/srv/hadoop$ ls -l
total 52
drwxr-xr-x 2 hduser hadoop  4096 nov 13 21:20 bin
drwxr-xr-x 4 hduser hadoop  4096 nov 13 21:20 etc
drwxr-xr-x 2 hduser hadoop  4096 nov 13 21:20 include
drwxr-xr-x 3 hduser hadoop  4096 nov 13 21:20 lib
drwxr-xr-x 2 hduser hadoop  4096 nov 13 21:20 libexec
-rw-r--r-- 1 hduser hadoop 15429 nov 13 21:20 LICENSE.txt
drwxr-xr-x 1 itam   staff     68 abr 24 00:54 logs
-rw-r--r-- 1 hduser hadoop   101 nov 13 21:20 NOTICE.txt
-rw-r--r-- 1 hduser hadoop  1366 nov 13 21:20 README.txt
drwxr-xr-x 2 hduser hadoop  4096 abr 22 07:07 sbin
drwxr-xr-x 4 hduser hadoop  4096 nov 13 21:20 share
```
Sí arranca el ssh:
```
root@d8e39de00234:/home/itam# service ssh status
s * sshd is not running
root@d8e39de00234:/home/itam# service ssh start
 * Starting OpenBSD Secure Shell server sshd
```
Pero no quiere levantar el hadoop porque no tiene los permisos correctos :(
```
root@d8e39de00234:/home/itam# su hduser
hduser@d8e39de00234:/home/itam$ start-dfs.sh
15/04/24 01:02:12 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Starting namenodes on [localhost]
localhost: starting namenode, logging to /srv/hadoop/logs/hadoop-hduser-namenode-d8e39de00234.out
localhost: /srv/hadoop/sbin/hadoop-daemon.sh: línea 159: /srv/hadoop/logs/hadoop-hduser-namenode-d8e39de00234.out: Permiso denegado
localhost: head: no se puede abrir «/srv/hadoop/logs/hadoop-hduser-namenode-d8e39de00234.out» para lectura: No existe el archivo o el directorio
localhost: /srv/hadoop/sbin/hadoop-daemon.sh: línea 177: /srv/hadoop/logs/hadoop-hduser-namenode-d8e39de00234.out: Permiso denegado
localhost: /srv/hadoop/sbin/hadoop-daemon.sh: línea 178: /srv/hadoop/logs/hadoop-hduser-namenode-d8e39de00234.out: Permiso denegado
localhost: starting datanode, logging to /srv/hadoop/logs/hadoop-hduser-datanode-d8e39de00234.out
localhost: /srv/hadoop/sbin/hadoop-daemon.sh: línea 159: /srv/hadoop/logs/hadoop-hduser-datanode-d8e39de00234.out: Permiso denegado
localhost: head: no se puede abrir «/srv/hadoop/logs/hadoop-hduser-datanode-d8e39de00234.out» para lectura: No existe el archivo o el directorio
localhost: /srv/hadoop/sbin/hadoop-daemon.sh: línea 177: /srv/hadoop/logs/hadoop-hduser-datanode-d8e39de00234.out: Permiso denegado
localhost: /srv/hadoop/sbin/hadoop-daemon.sh: línea 178: /srv/hadoop/logs/hadoop-hduser-datanode-d8e39de00234.out: Permiso denegado
```
Y esta vez se tardó un par de minutos en sacar este output, aunque podría ser que mi compu es lenta... Ahora sí hasta creé carpetas con los mismos nombres en los mismos lugares de mi compu que en tu ejemplo. Según yo ya está idéntico, no? No sé por qué toma a itam como el usuario default. No tiene mucho sentido :/

**Comment by nanounanue** [comment]
Debe de ser un problema de MacOSX y `boot2docker`

**Comment by felipegerard** [comment]
Eso parece, pero lo intrigante es: por qué elige a itam incluso cuando ponemos --user hduser? :/

**Comment by nanounanue** [comment]
@felipegerard mira [aquí](http://viget.com/extend/how-to-use-docker-on-os-x-the-missing-guide), sobre todo en la sección de **Problem: Mounting Volumes**, como dije es el  `boot2docker`...

**Comment by felipegerard** [comment]
Se ve bien! Lo pruebo y te digo qué tal me fue. Ya pasé la voz :)

**Comment by felipegerard** [comment]
Ya investigué un montón y después de mucho trabajo y esfuerzo, no llegué a nada. Yo creo que el problema viene de la imagen `docker-base`, que es en la que está basada la de hadoop y que sí tiene al usuario ITAM. No encontré la solución y por ejemplo [aquí](https://github.com/boot2docker/boot2docker/issues/581) se ve poco prometedor, aunque al parecer hay workarounds con SSH. Por ser ordenado, intenté correrlo sin montar las carpetas y entonces _sí tiene los permisos correctos!_:

```
$ docker run -ti --rm --user hduser \
>   -e "AUTHORIZED_SSH_PUBLIC_KEY=$(cat ~/.ssh/id_rsa.pub)" \
>   -p 2122:2122 -p 2181:2181 -p 39534:39534 -p 9000:9000 \
>   -p 50070:50070 -p 50010:50010 -p 50020:50020 -p 50075:50075 \
>   -p 50090:50090 -p 8030:8030 -p 8031:8031 -p 8032:8032 \
>   -p 8033:8033 -p 8088:8088 -p 8040:8040 -p 8042:8042 \
>   -p 13562:13562 -p 47784:47784 -p 10020:10020 -p 19888:19888 \
> nanounanue/docker-hadoop /bin/bash
hduser@515bc3952d2e:/home/itam$ cd
hduser@515bc3952d2e:~$ pwd
/home/hduser
hduser@515bc3952d2e:~$ ls
hdfs-data
hduser@515bc3952d2e:~$ ls -l
total 4
drwxr-xr-x 4 hduser hadoop 4096 Apr 28 21:13 hdfs-data
```

O incluso si lo corremos sin el `--user hduser` también tiene los permisos correctos:

```
$ docker run -ti --rm \
>   -e "AUTHORIZED_SSH_PUBLIC_KEY=$(cat ~/.ssh/id_rsa.pub)" \
>   -p 2122:2122 -p 2181:2181 -p 39534:39534 -p 9000:9000 \
>   -p 50070:50070 -p 50010:50010 -p 50020:50020 -p 50075:50075 \
>   -p 50090:50090 -p 8030:8030 -p 8031:8031 -p 8032:8032 \
>   -p 8033:8033 -p 8088:8088 -p 8040:8040 -p 8042:8042 \
>   -p 13562:13562 -p 47784:47784 -p 10020:10020 -p 19888:19888 \
> nanounanue/docker-hadoop /bin/bash
root@266a13321e80:/home/itam# cd /home/hduser/
root@266a13321e80:/home/hduser# ls -l
total 4
drwxr-xr-x 4 hduser hadoop 4096 Apr 28 21:18 hdfs-data
```

Pero, por supuesto, las carpetas no están montadas... Qué haremos? Una opción es correr todo dentro del docker, otra es montarlas vía ssh pero no estoy seguro de cómo y no quiero arruinar las cosas (ya tuve que reinstalar `boot2docker` en mi búsqueda de un _fix_). La última es correrlo localmente, pero no tendríamos los logs dentro de la compu _host_. Un _workaround_ podría ser unir otra carpeta al _host_ y al final de la sesión copiar lo que se genere en las carpetas de Hadoop a esta carpeta para tener la información en el _host_.

**Comment by nanounanue** [comment]
Espero que con la nueva versión de `docker-hadoop` quede
